package gofns

import "regexp"

type regionRule struct {
	re   *regexp.Regexp
	code int
}

// regionRules проверяются по порядку, первое совпадение определяет код региона.
var regionRules = []regionRule{
	// города ----------------------------------------------------------------------------------------------------
	{regexp.MustCompile(`(?si)[^а-я]Санкт-Петербург[а]*([^а-я]|$)`), 78},
	{regexp.MustCompile(`(?si)[^а-я]Москв[аы]([^а-я]|$)`), 77},
	{regexp.MustCompile(`(?si)[^а-я]Севастопол[ья]([^а-я]|$)`), 92},

	// области ----------------------------------------------------------------------------------------------------
	{regexp.MustCompile(`(?si)Амурск(ая|ой)\s+обл`), 28},
	{regexp.MustCompile(`(?si)Архангельск(ая|ой)\s+обл`), 29},
	{regexp.MustCompile(`(?si)Астраханск(ая|ой)\s+обл`), 30},
	{regexp.MustCompile(`(?si)Белгородск(ая|ой)\s+обл`), 31},
	{regexp.MustCompile(`(?si)Брянск(ая|ой)\s+обл`), 32},
	{regexp.MustCompile(`(?si)Владимирск(ая|ой)\s+обл`), 33},
	{regexp.MustCompile(`(?si)Волгоградск(ая|ой)\s+обл`), 34},
	{regexp.MustCompile(`(?si)Вологодск(ая|ой)\s+обл`), 35},
	{regexp.MustCompile(`(?si)Воронежск(ая|ой)\s+обл`), 36},
	{regexp.MustCompile(`(?si)Ивановск(ая|ой)\s+обл`), 37},
	{regexp.MustCompile(`(?si)Иркутск(ая|ой)\s+обл`), 38},
	{regexp.MustCompile(`(?si)Калининградск(ая|ой)\s+обл`), 39},
	{regexp.MustCompile(`(?si)Калужск(ая|ой)\s+обл`), 40},
	{regexp.MustCompile(`(?si)Кемеровск(ая|ой)\s+обл`), 42},
	{regexp.MustCompile(`(?si)Кировск(ая|ой)\s+обл`), 43},
	{regexp.MustCompile(`(?si)Костромск(ая|ой)\s+обл`), 44},
	{regexp.MustCompile(`(?si)Курганск(ая|ой)\s+обл`), 45},
	{regexp.MustCompile(`(?si)Курск(ая|ой)\s+обл`), 46},
	{regexp.MustCompile(`(?si)Ленинградск(ая|ой)\s+обл`), 47},
	{regexp.MustCompile(`(?si)Липецк(ая|ой)\s+обл`), 48},
	{regexp.MustCompile(`(?si)Магаданск(ая|ой)\s+обл`), 49},
	{regexp.MustCompile(`(?si)Московск(ая|ой)\s+обл`), 50},
	{regexp.MustCompile(`(?si)Мурманск(ая|ой)\s+обл`), 51},
	{regexp.MustCompile(`(?si)Нижегородск(ая|ой)\s+обл`), 52},
	{regexp.MustCompile(`(?si)Новгородск(ая|ой)\s+обл`), 53},
	{regexp.MustCompile(`(?si)Новосибирск(ая|ой)\s+обл`), 54},
	{regexp.MustCompile(`(?si)[^а-я]Омск(ая|ой)\s+обл`), 55},
	{regexp.MustCompile(`(?si)Оренбургск(ая|ой)\s+обл`), 56},
	{regexp.MustCompile(`(?si)Орловск(ая|ой)\s+обл`), 57},
	{regexp.MustCompile(`(?si)Пензенск(ая|ой)\s+обл`), 58},
	{regexp.MustCompile(`(?si)псковск(ая|ой)\s+обл`), 60},
	{regexp.MustCompile(`(?si)Ростовск(ая|ой)\s+обл`), 61},
	{regexp.MustCompile(`(?si)Рязанск(ая|ой)\s+обл`), 62},
	{regexp.MustCompile(`(?si)Самарск(ая|ой)\s+обл`), 63},
	{regexp.MustCompile(`(?si)Саратовск(ая|ой)\s+обл`), 64},
	{regexp.MustCompile(`(?si)Сахалинск(ая|ой)\s+обл`), 65},
	{regexp.MustCompile(`(?si)Свердловск(ая|ой)\s+обл`), 66},
	{regexp.MustCompile(`(?si)Смоленск(ая|ой)\s+обл`), 67},
	{regexp.MustCompile(`(?si)Тамбовск(ая|ой)\s+обл`), 68},
	{regexp.MustCompile(`(?si)Тверск(ая|ой)\s+обл`), 69},
	{regexp.MustCompile(`(?si)Томск(ая|ой)\s+обл`), 70},
	{regexp.MustCompile(`(?si)Тульск(ая|ой)\s+обл`), 71},
	{regexp.MustCompile(`(?si)Тюменск(ая|ой)\s+обл`), 72},
	{regexp.MustCompile(`(?si)Ульяновск(ая|ой)\s+обл`), 73},
	{regexp.MustCompile(`(?si)Челябинск(ая|ой)\s+обл`), 74},
	{regexp.MustCompile(`(?si)Ярославск(ая|ой)\s+обл`), 76},
	{regexp.MustCompile(`(?si)(Еврейск(ая|ой)\s+(АО|автономн(ая|ой))|[^а-я]ЕАО[^а-я])`), 79},
	{regexp.MustCompile(`(?si)(\s|^)Ненецк(ий|ого)\s+(автономн(ый|ого)|ао)`), 83},
	{regexp.MustCompile(`(?si)Ханты-Мансийск(ий|ого)\s+(автономн(ый|ого)|ао)`), 86},
	{regexp.MustCompile(`(?si)Чукотск(ий|ого)\s+(автономн(ый|ого)|ао)`), 87},
	{regexp.MustCompile(`(?si)(Ямало\s*-\s*Ненецк(ий|ого)\sа|ЯНАО)`), 89},

	// края -----------------------------------------------------------------------------------------------
	{regexp.MustCompile(`(?si)алтайск(ий|ого)\s+кра[йя]`), 22},
	{regexp.MustCompile(`(?si)Краснодарск(ий|ого)\s+кра[йя]`), 23},
	{regexp.MustCompile(`(?si)Красноярск(ий|ого)\s+кра[йя]`), 24},
	{regexp.MustCompile(`(?si)Приморск(ий|ого)\s+кра[йя]`), 25},
	{regexp.MustCompile(`(?si)Ставропольск(ий|ого)\s+кра[йя]`), 26},
	{regexp.MustCompile(`(?si)Хабаровск(ий|ого)\s+кра[йя]`), 27},
	{regexp.MustCompile(`(?si)Камчатск(ий|ого)\s+кра[йя]`), 41},
	{regexp.MustCompile(`(?si)пермск(ий|ого)\s+кра[йя]`), 59},
	{regexp.MustCompile(`(?si)Забайкальск(ий|ого)\s+кра[йя]`), 75},

	// республики --------------------------------------------------------------------------------------------
	{regexp.MustCompile(`(?si)Республик[иа]\s+Адыгея`), 1},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Башкортостан`), 2},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Бурятия`), 3},
	{regexp.MustCompile(`(?si)Республик[иа]\s+алтай`), 4},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Дагестан`), 5},
	{regexp.MustCompile(`(?si)Республик[иа]\s+ингушетия`), 6},
	{regexp.MustCompile(`(?si)Кабардино-Балкарск(ая|ой)`), 7},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Калмыкия`), 8},
	{regexp.MustCompile(`(?si)Карачаево-Черкесск(ая|ой)`), 9},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Карелия`), 10},
	{regexp.MustCompile(`(?si)Республик[иа]\s+коми`), 11},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Марий[\s\-]Эл`), 12},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Мордови[ия]`), 13},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Саха`), 14},
	{regexp.MustCompile(`(?si)РСО-Алания`), 15},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Татарстан`), 16},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Тыва`), 17},
	{regexp.MustCompile(`(?si)Удмуртск(ая|ой)\s+Республик`), 18},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Хакаси[яи]`), 19},
	{regexp.MustCompile(`(?si)Чеченск(ая|ой)\s+Республик`), 20},
	{regexp.MustCompile(`(?si)Чувашск(ая|ой)\s+Республик`), 21},
	{regexp.MustCompile(`(?si)Республик[иа]\s+Крым`), 91},

	// Дополнительные города --------------------------------------------------------------------------------
	{regexp.MustCompile(`(?si)[^а-я]Майкоп[а]*([^а-я]|$)`), 1},
	{regexp.MustCompile(`(?si)[^а-я]Улан-Удэ([^а-я]|$)`), 3},
	{regexp.MustCompile(`(?si)[^а-я](Махачкал[аы]|Буйнакск[а]*|Хасавюрт[а]*|Дербент[а]*)([^а-я]|$)`), 5},
	{regexp.MustCompile(`(?si)[^а-я]Назран[ьи]([^а-я]|$)`), 6},
	{regexp.MustCompile(`(?si)[^а-я]Нальчик[а]*([^а-я]|$)`), 7},
	{regexp.MustCompile(`(?si)[^а-я](Черкесск|Карачаевск)[а]*([^а-я]|$)`), 9},
	{regexp.MustCompile(`(?si)[^а-я]Петрозаводск[а]*([^а-я]|$)`), 10},
	{regexp.MustCompile(`(?si)[^а-я]Сыктывкар[а]*([^а-я]|$)`), 11},
	{regexp.MustCompile(`(?si)[^а-я]Саранск[а]*([^а-я]|$)`), 13},
	{regexp.MustCompile(`(?si)[^а-я]Владикавказ[а]*([^а-я]|$)`), 15},
	{regexp.MustCompile(`(?si)[^а-я](Набережные\sЧелны|Казан[ьи])([^а-я]|$)`), 16},
	{regexp.MustCompile(`(?si)[^а-я]Ижевск[а]*([^а-я]|$)`), 18},
	{regexp.MustCompile(`(?si)[^а-я]Абакан[а]*([^а-я]|$)`), 19},
	{regexp.MustCompile(`(?si)[^а-я](Новочебоксарск[а]*|Алатыр[ья])([^а-я]|$)`), 21},
	{regexp.MustCompile(`(?si)[^а-я](Анап[аы]|Армавир[а]*|Новороссийск[а]*|Ейск[а]*|Сочи|Темрюк[а]*|Геленджик[а]*)([^а-я]|$)`), 23},
	{regexp.MustCompile(`(?si)(?si)[^а-я](Красноярск|Зеленогорск|Минусинск|Норильск)[ае]*([^а-я]|$)`), 24},
	{regexp.MustCompile(`(?si)[^а-я]Владивосток[а]*([^а-я]|$)`), 25},
	{regexp.MustCompile(`(?si)[^а-я]Ставропол[ья]([^а-я]|$)`), 26},
	{regexp.MustCompile(`(?si)[^а-я](Хабаровск[а]*|Комсомольск[а]*-на-Амуре)([^а-я]|$)`), 27},
	{regexp.MustCompile(`(?si)[^а-я]Благовещенск[а]*([^а-я]|$)`), 28},
	{regexp.MustCompile(`(?si)[^а-я]Архангельск[а]*([^а-я]|$)`), 29},
	{regexp.MustCompile(`(?si)[^а-я]Астрахан[ьи]([^а-я]|$)`), 30},
	{regexp.MustCompile(`(?si)[^а-я]Белгород[а]*([^а-я]|$)`), 31},
	{regexp.MustCompile(`(?si)[^а-я]Брянск[а]*([^а-я]|$)`), 32},
	{regexp.MustCompile(`(?si)[^а-я](Владимир[а]*|Муром[а]*|Суздал[ья]|Гусь-Хрустальн(ый|ого))([^а-я]|$)`), 33},
	{regexp.MustCompile(`(?si)[^а-я]Волгоград[а]*([^а-я]|$)`), 34},
	{regexp.MustCompile(`(?si)[^а-я](Вологд[аы]|Черепов(ца|ец))([^а-я]|$)`), 35},
	{regexp.MustCompile(`(?si)[^а-я]Воронеж[а]*([^а-я]|$)`), 36},
	{regexp.MustCompile(`(?si)[^а-я](Иркутск|Ангарск|Саянск)[а]*([^а-я]|$)`), 38},
	{regexp.MustCompile(`(?si)[^а-я]Калининград[а]*([^а-я]|$)`), 39},
	{regexp.MustCompile(`(?si)[^а-я]Петропавловск-Камчатск(ий|а)([^а-я]|$)`), 41},
	{regexp.MustCompile(`(?si)[^а-я]Кемеров[оа]([^а-я]|$)`), 42},
	{regexp.MustCompile(`(?si)[^а-я]Киров([^а-я]|$)`), 43},
	{regexp.MustCompile(`(?si)[^а-я]Костром[аы]([^а-я]|$)`), 44},
	{regexp.MustCompile(`(?si)[^а-я]Курск[а]*([^а-я]|$)`), 46},
	{regexp.MustCompile(`(?si)[^а-я]Липецк[а]*([^а-я]|$)`), 48},
	{regexp.MustCompile(`(?si)[^а-я](Клин|Химки)([^а-я]|$)`), 50},
	{regexp.MustCompile(`(?si)[^а-я]Мурманск[а]*([^а-я]|$)`), 51},
	{regexp.MustCompile(`(?si)[^а-я](Нижний\s|н[\s.]*)новгород([^а-я]|$)`), 52},
	{regexp.MustCompile(`(?si)[^а-я]Новосибирск[а]*([^а-я]|$)`), 54},
	{regexp.MustCompile(`(?si)[^а-я]Омск[а]*([^а-я]|$)`), 55},
	{regexp.MustCompile(`(?si)[^а-я]Оренбург[а]*([^а-я]|$)`), 56},
	{regexp.MustCompile(`(?si)[^а-я](Ор[её]л|Орла)([^а-я]|$)`), 57},
	{regexp.MustCompile(`(?si)[^а-я]Пенз[аы]([^а-я]|$)`), 58},
	{regexp.MustCompile(`(?si)[^а-я](Перм[ьи]|Соликамск)([^а-я]|$)`), 59},
	{regexp.MustCompile(`(?si)[^а-я](Псков[а]*|Великие\s+Луки)([^а-я]|$)`), 60},
	{regexp.MustCompile(`(?si)[^а-я]Ростов[а]*-на-Дону([^а-я]|$)`), 61},
	{regexp.MustCompile(`(?si)[^а-я]Рязан[ьи]([^а-я]|$)`), 62},
	{regexp.MustCompile(`(?si)[^а-я](Самар[аы]|Тольятти)([^а-я]|$)`), 63},
	{regexp.MustCompile(`(?si)[^а-я](Екатеринбург|Первоуральск)[а]*([^а-я]|$)`), 66},
	{regexp.MustCompile(`(?si)[^а-я]Смоленск[а]*([^а-я]|$)`), 67},
	{regexp.MustCompile(`(?si)[^а-я]Тамбов[а]*([^а-я]|$)`), 68},
	{regexp.MustCompile(`(?si)[^а-я]Томск[а]*([^а-я]|$)`), 70},
	{regexp.MustCompile(`(?si)[^а-я]Тул[аы]([^а-я]|$)`), 71},
	{regexp.MustCompile(`(?si)[^а-я]Тюмен[ьи]([^а-я]|$)`), 72},
	{regexp.MustCompile(`(?si)[^а-я]Ульяновск[а]*([^а-я]|$)`), 73},
	{regexp.MustCompile(`(?si)[^а-я](Челябинск|Магнитогорск)[а]*([^а-я]|$)`), 74},
	{regexp.MustCompile(`(?si)[^а-я]Чит[аы]([^а-я]|$)`), 75},
	{regexp.MustCompile(`(?si)[^а-я]Ярославл[ья]([^а-я]|$)`), 76},
	{regexp.MustCompile(`(?si)[^а-я]Ломоносов([^а-я]|$)`), 78},
	{regexp.MustCompile(`(?si)[^а-я](Нижневартовск|Сургут|Ханты-Мансийск)[а]*([^а-я]|$)`), 86},
}

func DetermineRegionCodeByAddress(addr string) (code int) {
	for _, r := range regionRules {
		if r.re.MatchString(addr) {
			return r.code
		}
	}
	return 0
}
